### ISSUE TITLE
fails for custom set npm prefix

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/global-prefix#2]
Currently in my Arch i set it to `/usr/local`, because default installs of node and npm uses `/usr`.
One way could be using `require('rc')('npm').prefix` (pretty faster and easier than spawnSync) and then fallback to `process.execPath` and `DESTDIR`

or if you want [npm-prefix](http://npm.im/npm-prefix), but I don't like it that it does `../../` thing.

**Comment by jonschlinkert** [comment]
But that's not related this project is it? This provides the default paths used by npm. 

> Get the npm global path prefix. Same code used internally by npm

**Comment by tunnckoCore** [comment]
Hm. That's okey, but custom prefix again is global prefix, lol. It is lil' bit.. hm.
To me it is logical when npm support custom prefix, this one also to support it and almost worth nothing. It would help for better resolving global modules, imo.
I have few libs that depends on that module - `get-installed-path`, `detect-installed` and `is-installed`.

**Comment by tunnckoCore** [comment]
Also this package is used in `global-modules` which is with pretty clear description _"the directory used by npm for globally installed npm modules."_

**Comment by jonschlinkert** [comment]
so, should there be another lib called `custom-prefix` that uses a custom prefix if defined and falls back to global-prefix?

> but custom prefix again is global prefix,

but, if I recall correctly that logic is handled by npm outside of the global prefix logic.

**Comment by jonschlinkert** [comment]
fwiw, I'm not necessarily opposed to adding logic for custom prefix. it depends on how much overhead it adds

**Comment by tunnckoCore** [comment]
> another lib called `custom-prefix`

that's maybe the easiest way, but less meaningful and logical. maybe some other name at least, idk.

> if I recall correctly that logic is handled by npm outside of the global prefix logic.

hm.. good point.

**Comment by jonschlinkert** [comment]
@tunnckoCore can you check and see if this works for you now?

**Comment by tunnckoCore** [comment]
I believe it worked before #8 or I may be wrong, but nevermind. I'll try asap, because i'm busy with university.

**Comment by jonschlinkert** [comment]
> because i'm busy with university.

don't worry about this! university is much more important than this

**Comment by jonschlinkert** [comment]
Ok closing based on the assumption that it's working for you. If necessary we can reopen

**Comment by tunnckoCore** [comment]
Yep, works in first glance. :) Sorry for the delay.
