### ISSUE TITLE
ini 1.3.5 dependency has prototype pollution

### ISSUE THREAD

**Issue by adityapant1286** [jonschlinkert/global-prefix#28]
There is low-level vulnerability for `ini 1.3.5` dependency. Unfortunately, this version has seen the end of life and the current version is 2.0.0.
Is it possible to update the dependency to the latest version?

**Comment by stieben** [comment]
This looks like a duplicate of #26.

**Comment by phated** [comment]
The caret (`^`) in the semver range actually means you will already get that bugfix patch! You just need to remove your lockfile and reinstall your dependencies.

**Comment by phated** [comment]
The v4.0.0 release is now using `^4.1.3` of ini
