### ISSUE TITLE
Uncaught TypeError: isWindows is not a function

### ISSUE THREAD

**Issue by vjpr** [jonschlinkert/global-prefix#7]
This has broken the `cwd` when running with webpack.

`** ./~/cwd/~/find-pkg/~/find-file-up/~/resolve-dir/~/global-modules/~/global-prefix/index.js`

```
} else if (isWindows === true || isWindows()) {
```

`is-windows` module returns a value, not a function.

**Comment by jonschlinkert** [comment]
this should be fixed
